# Generated by Django 4.2 on 2023-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': '', 'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(related_name='user_interest', to='user.interest'),
        ),
    ]
