# Generated by Django 4.2 on 2023-05-03 07:35

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_userprofile_phone_number_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document',
            field=models.FileField(default=None, upload_to=user.models.get_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is User Deleted'),
        ),
    ]
