# Generated by Django 4.2 on 2023-05-03 07:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_document_alter_userprofile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=user.models.get_upload_path),
        ),
    ]
