# Generated by Django 4.2 on 2023-05-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
