# Generated by Django 4.2 on 2023-05-03 08:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_userprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHomeOfficeGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_off_gap', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Line Vector from home to office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_userhomeoffice', to='user.userprofile')),
            ],
            options={
                'verbose_name': 'User Home Office Gap',
                'verbose_name_plural': 'Users Home Office Gap',
            },
        ),
    ]
