# Generated by Django 4.2 on 2023-05-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_options'),
        ('hometoofficelinevector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhomeofficegap',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_userhomeoffice', to='user.userprofile'),
        ),
    ]
