# Generated by Django 4.2 on 2023-05-04 05:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometoofficelinevector', '0002_alter_userhomeofficegap_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhomeofficegap',
            name='home_off_gap',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Line Vector from home to office'),
        ),
    ]
